[tool.poetry]
name = "source"
version = "0.1.0"
description = "Python scripts"
authors = ["RenChu Wang <patrick1031wang@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
ray = {extras = ["default"], version = "^2.4.0"}

[tool.poetry.group.dev.dependencies]
autoflake = "^1.4"
black = "^23.3.0"
mypy = "^1.4.1"
ipython = "^8.14.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
