[tool.poetry]
name = "python"
version = "0.1.0"
description = "Python scripts"
authors = ["RenChu Wang <patrick1031wang@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
ray = {extras = ["default"], version = "^2.4.0"}

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.3.0"
autoflake = "^1.4"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
