[project]
name = "python"
version = "0.0.0"
description = "Python scripts"
authors = [
    {name = "RenChu Wang", email = "patrick1031wang@gmail.com"},
]
dependencies = []
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = "false"

[tool.pdm.dev-dependencies]
format = [
    "autoflake>=2.2.1",
    "black>=24.2.0",
    "isort>=5.13.2",
]
type = [
    "mypy>=1.8.0",
]
