name: Format
on: [push]
jobs:
  format-check:
    name: 📀 Formatting
    runs-on: ubuntu-latest
    steps:
      # Global part
      - name: 🔔 Check out
        uses: actions/checkout@v3

      # C++ part
      - name: 🏗️ 🏃 clang-format
        uses: DoozyX/clang-format-lint-action@v0.18
        with:
          source: ./cpp
          extensions: h,c,hpp,cpp
          clangFormatVersion: 18

      # Python part
      - name: 🏗️ python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: ⬇️ Python Poetry
        uses: pdm-project/setup-pdm@v3

      - name: ⬇️ Python Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
          installer-parallel: true

      - name: 🏃 autoflake, isort, black
        working-directory: ./python
        run: |
          poetry run autoflake --check .
          poetry run isort --check .
          poetry run black --check .
