name: Format
on: [push]
jobs:
  format-check:
    name: 📀 Formatting
    runs-on: ubuntu-latest
    steps:
      # Global part
      - name: 🔔 Check out
        uses: actions/checkout@v3

      # C++ part
      - name: 🏗️ 🏃 clang-format
        uses: DoozyX/clang-format-lint-action@v0.16
        with:
          source: ./cpp
          extensions: h,c,hpp,cpp
          clangFormatVersion: 16

      # Python part
      - name: 🏗️ python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v3

      - name: ⬇️ Python Dependencies
        run: pdm install
        working-directory: ./python

      - name: 🚂 Activate environment
        run: echo "$(pdm venv --path in-project)/bin" >> $GITHUB_PATH
        working-directory: ./python

      - name: 🏃 autoflake, isort, black
        working-directory: ./python
        run: |
          autoflake --check .
          isort --check .
          black --check .
