name: Format
on: [push]
jobs:
  format-check:
    name: 📀 Formatting
    runs-on: ubuntu-latest
    steps:
      # Global part
      - name: 🔔 Check out
        uses: actions/checkout@v3

      # C++ part
      - name: 🏗️ 🏃 clang-format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: ./cxx
          extensions: h,c,hxx,cxx
          clangFormatVersion: 14

      # Dart part
      - name: 🏗️ dart
        uses: dart-lang/setup-dart@v1
      - name: 🏃 dart format
        working-directory: ./dart
        run: dart format --output=none --set-exit-if-changed .

      # Python part
      - name: 🏗️ python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v3

      - name: ⬇️ Python Dependencies
        run: pdm install
        working-directory: ./python

      - name: 🚂 Activate environment
        run: echo "$(pdm venv --path in-project)/bin" >> $GITHUB_PATH
        working-directory: ./python

      - name: 🏃 autoflake, isort, black
        working-directory: ./python
        run: |
          autoflake --check .
          isort --check .
          black --check .
