name: Format
on: [push]
jobs:
  format-all:
    runs-on: ubuntu-latest
    steps:
      # Global part
      - name: 🔔 Check out
        uses: actions/checkout@v2

      # Clang-format (C/C++) part
      - name: 🏗️ 🏃 clang-format
        uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: ./c
          extensions: h,cpp,c
          clangFormatVersion: 11
          inplace: True

      # Dart part
      - name: 🏗️ dart runtime
        uses: dart-lang/setup-dart@v1
      - name: 🏃 dart format
        working-directory: ./dart
        run: dart format .

      # Golang part
      - name: 🏗️ go runtime
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13.1
      - name: 🏃 go fmt
        run: go fmt
        working-directory: ./go

      # JavaScript/TypeScript part
      - name: 🏗️ node
        uses: actions/setup-node@v2
        with:
          node-verion: 16
      - name: ⬇️ all packages
        working-directory: ./javascript
        run: npm install
      - name: 🏃 prettier
        working-directory: ./javascript
        run: ./node_modules/prettier/bin-prettier.js --write .

      - name: ⬇️ all packages
        working-directory: ./typescript
        run: npm install
      - name: 🏃 prettier
        working-directory: ./typescript
        run: ./node_modules/prettier/bin-prettier.js --write .

      # Black (Python) part
      - name: 🏗️ python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ⬇️ Python Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12
      - name: ⬇️ Python Dependencies
        working-directory: ./python
        run: poetry install
      - name: 🏃 autoflake, isort, black
        working-directory: ./python
        run: |
          poetry run autoflake -ir . --remove-all-unused-imports
          poetry run isort --profile black .
          poetry run black .

      # Rust part
      - name: 🏗️ Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: 🏃 cargo fmt
        working-directory: ./rust
        run: cargo fmt

      # Add and commit all
      - name: ⬆️ Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "🤖 RenTrueWang thinks you forgot to format your code!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
