name: Format
on: [push]
jobs:
  format-check:
    name: 📀 Formatting
    runs-on: ubuntu-latest
    steps:
      # Global part
      - name: 🔔 Check out
        uses: actions/checkout@v3

      # C++ part
      - name: 🏗️ 🏃 clang-format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: ./cxx
          extensions: h,c,hxx,cxx
          clangFormatVersion: 14

      # Go part
      - name: 🏗️ go runtime
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: 🏃 go fmt
        working-directory: ./go
        run: gofmt -e . > /dev/null

      # Python part
      - name: 🏗️ python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v3
      - name: ⬇️ Python Dependencies
        run: pdm install
        working-directory: ./python
      - name: 🚂 Activate environment
        run: echo "$(pdm venv --path in-project)/bin" >> $GITHUB_PATH
        working-directory: ./python
      - name: 🏃 autoflake, isort, black
        working-directory: ./python
        run: |
          autoflake -cr . --remove-all-unused-imports
          isort --check .
          black --check .
